config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :charts, only: :index do
    get :day, on: :member
  end
  resources :prices, only: %i(index)
  resources :my_trades, only: %i(create) do
    member do
      put :cancel
    end
  end
  resources :my_trade_ships, only: %i(index)
  namespace :admin do
    resources :my_trades, only: %i(index) do
      delete :destroy_all, on: :collection
    end
  end
  namespace :api do
    resource :disparities, only: :show
    post 'run_one_scalping' => 'scalpings#create', as: :run_one_scalping
    post 'run_endless_scalping' => 'daemon_scalpings#create', as: :run_endless_scalping
    post 'run_remove_waiting_trading' => 'remove_waiting_trades#create', as: :run_remove_waiting_trading
  end
  namespace :resque do
    resources :workers, only: %i(index)
    resources :worker_statuses, only: %i(index)
    resources :jobs, only: %i(destroy), param: :pid do
      delete :destroy_all, on: :collection
    end
  end
  resources :scalping_tasks, only: %i(index)
  resource :setting, only: %i(edit update)
  resources :results, only: :index do
    post :recalc, on: :collection
  end
  resources :api_call_logs, only: :index
  resources :preorder_snapshots do
    post :import_to_bf, on: :member
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/views/top/_info_and_action.html.slim
div style='height:50px'
  span data-role='buy_1'
  br
  span data-role='buy_5'

table border=1 style='text-align: center;'
  tr
    th 最終取引価格
    th チャートの形
    th public API(上限:500回/分)
    th private API(上限:200回/分)
  tr
    td
      h3#last_trade_price
    td#price_directions
    td
      span#public_api_call_logs_count
      |/分
    td
      span#private_api_call_logs_count
      |/分
  tr
    th BF負荷
    /th 取引所ステータス
    th BFサーバステータス
    th
    th
  tr
    td
      div#health_meter style='margin-left: auto; marign-right: auto;'
    /td#status_health_message
    td#bf_status
    th
    th
  tr
    th ロット数
    th 利益値幅
    th
    th
  tr
    td = BF::Setting.record.order_size
    td = BF::Setting.record.order_range
    th
    th
  tr
    th 保有枚数
    th
    th
    th
  tr
    td = BF::MyTradeShip.running.includes(:buy_trade).map { |x| x.buy_trade.size }.sum.to_f
    td
    th
    th


table.mt20 border=1 style='text-align: center;'
  tr
    th colspan=3 ジョブ
  tr
    td = button_to '自動発注', api_run_one_scalping_path, method: :post, remote: true, class: 'button job'
    td = button_to '繰り返し自動発注', api_run_endless_scalping_path, method: :post, remote: true, class: 'button job'
    td = button_to '約定確認', api_run_remove_waiting_trading_path(s: 2), method: :post, remote: true, class: 'button job'
  tr
    td = button_to '非同期ジョブの全停止', destroy_all_resque_jobs_path, method: :delete, remote: true, class: 'button job'
    td
    td
  tr
    th colspan=3 設定変更
  tr
    td = button_to 'ロット数を0.01にする', setting_path(bf_setting: { order_size: '0.01' }, from: root_url), method: :patch, class: 'button update'
    td = button_to 'ロット数を0.1にする', setting_path(bf_setting: { order_size: '0.1' }, from: root_url), method: :patch, class: 'button update'
    td = button_to 'ロット数を0.2にする', setting_path(bf_setting: { order_size: '0.2' }, from: root_url), method: :patch, class: 'button update'

app/views/top/index.html.slim
= content_for(:header_bottom) do
  div style='text-align: right'
    | 最終取得日時
    b#last_trade_at

.table.mt20
  .table-cell.left#price_table
  .table-cell.right#right_column
    = render 'info_and_action'

div#disparity
table
  tr
    td
      #worker_statuses
    td
      #worker_button = link_to 'show jobs', '#'
      #workers
div#my_trade_table

javascript:
  defultBodyColor = $('body').css('background-color');
  $(function() {
    $.ajax('/prices.js', { type: 'GET', timeout: 1000 }).success(function(){
      build_trade_link();
    })
    setTimeout($.ajax('/api_call_logs.js', { type: 'GET', timeout: 500 }), 500);
    setTimeout($.ajax('/my_trade_ships.js', { type: 'GET', timeout: 500 }), 1000);
    setTimeout($.ajax('/resque/worker_statuses.js', { type: 'GET', timeout: 1000 }), 1500);

    #{"$.ajax('/api/disparities.js', { type: 'GET', timeout: 1000 });".html_safe if BF::Setting.record.enabled_calc_disparity}

    setTimeout(function (){
      setInterval(function(){
        $.ajax('/prices.js', { type: 'GET', timeout: 1500 }).
          success(function(data, textStatus, jqXHR) { $('body').css('background-color', defultBodyColor) }).
          fail(function(jqXHR, textStatus, errorThrown) { $('body').css('background-color', 'yellow') });
      }, 1200);

      setInterval(function(){
        $.ajax('/api_call_logs.js', { type: 'GET', timeout: 500 });
      }, 2000);

      setInterval(function(){
        $.ajax('/resque/worker_statuses.js', { type: 'GET', timeout: 1000 });
        build_trade_link()
      }, 5000);

      setInterval(function(){
        $.ajax('/my_trade_ships.js', { type: 'GET', timeout: 1000 });
      }, 10000);
    }, 2000);

    #{"setInterval(function(){ $.ajax('/api/disparities.js', { type: 'GET', timeout: 1000 }); }, 2000);".html_safe if BF::Setting.record.enabled_calc_disparity}
  });