config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :charts, only: :index do
    get :day, on: :member
  end
  resources :prices, only: %i(index)
  resources :my_trades, only: %i(create) do
    member do
      put :cancel
    end
  end
  resources :my_trade_ships, only: %i(index)
  namespace :admin do
    resources :my_trades, only: %i(index) do
      delete :destroy_all, on: :collection
    end
  end
  namespace :api do
    resource :disparities, only: :show
    post 'run_one_scalping' => 'scalpings#create', as: :run_one_scalping
    post 'run_endless_scalping' => 'daemon_scalpings#create', as: :run_endless_scalping
    post 'run_remove_waiting_trading' => 'remove_waiting_trades#create', as: :run_remove_waiting_trading
  end
  namespace :resque do
    resources :workers, only: %i(index)
    resources :worker_statuses, only: %i(index)
    resources :jobs, only: %i(destroy), param: :pid do
      delete :destroy_all, on: :collection
    end
  end
  resources :scalping_tasks, only: %i(index)
  resource :setting, only: %i(edit update)
  resources :results, only: :index do
    post :recalc, on: :collection
  end
  resources :api_call_logs, only: :index
  resources :preorder_snapshots do
    post :import_to_bf, on: :member
  end
end

app/models/preorder_snapshot.rb
# url_forでBFネームスペースがつくと名前付きrouteとパスが長くなるので
# BFネームスペースをとったクラスを定義する
class PreorderSnapshot < BF::PreorderSnapshot
end

app/controllers/preorder_snapshots_controller.rb
class PreorderSnapshotsController < ApplicationController
  def index
    @snapshots = PreorderSnapshot.summary.order(id: :desc).page(params[:page]).select(:restored)
  end

  def new
    @snapshot = PreorderSnapshot.new
  end

  def show
    @snapshot = PreorderSnapshot.find(params[:id])
    @preorders = @snapshot.preorders.order(id: :desc)
  end

  def create
    @snapshot = PreorderSnapshot.new(preorder_snapshot_params)
    if @snapshot.save
      @snapshot.export_from_bf!
      redirect_to preorder_snapshots_path, notice: 'BFサーバから注文を取得することに成功しました'
    else
      render :new
    end
  end

  def import_to_bf
    unless PreorderSnapshot.order_empty?
      redirect_to preorder_snapshot_path(params[:id]), flash: { error: 'すでに注文が登録されているので処理を中止しました' }
      return
    end

    PreorderSnapshot.find(params[:id]).import_to_bf!
    redirect_to preorder_snapshot_path(params[:id]), notice: 'BFサーバから注文の反映に成功しました'
  end

  private

  def preorder_snapshot_params
    params.fetch(:preorder_snapshot).permit!
  end
end

app/views/preorder_snapshots/index.html.slim
h1 PreorderSnapshots

p = link_to '注文を取得する', new_preorder_snapshot_path

= paginate @snapshots

table border=1
  tr
    th id
    th memo
    th 作成日
    th 売り数
    th 買い数
    th 合計数量
    th 平均金額
    th 復元済み/未
  - @snapshots.each do |snapshot|
    tr
      td = link_to snapshot.id, preorder_snapshot_path(snapshot)
      td = snapshot.memo
      td = snapshot.created_at.strftime('%Y/%m/%d')
      td = snapshot.count_sell
      td = snapshot.count_buy
      td = snapshot.sum_size
      td = snapshot.avg_price
      td = snapshot.restored ? :済み : :未だ

= paginate @snapshots

app/views/preorder_snapshots/new.html.slim
h1 PreorderSnapshots

= form_for @snapshot do |f|
  p
    = f.label :memo
    = f.text_field :memo
  p
    = f.submit

app/views/preorder_snapshots/show.html.slim
h1 PreorderSnapshot
= link_to '戻る', preorder_snapshots_path

p = link_to '注文を反映する(破壊的)', import_to_bf_preorder_snapshot_path(@snapshot), data: { confirm: 'BFサーバに注文を送りますが本当にいいですか？' }, method: :post

table border=1
  tr
    th id
    th 売り/買い
    th 数量
    th 金額
  - @preorders.each do |preorder|
    tr
      td = preorder.id
      td = preorder.kind
      td = preorder.size
      td = preorder.price