config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :charts, only: :index do
    get :day, on: :member
  end
  resources :prices, only: %i(index)
  resources :my_trades, only: %i(create) do
    member do
      put :cancel
    end
  end
  resources :my_trade_ships, only: %i(index)
  namespace :admin do
    resources :my_trades, only: %i(index) do
      delete :destroy_all, on: :collection
    end
  end
  namespace :api do
    resource :disparities, only: :show
    post 'run_one_scalping' => 'scalpings#create', as: :run_one_scalping
    post 'run_endless_scalping' => 'daemon_scalpings#create', as: :run_endless_scalping
    post 'run_remove_waiting_trading' => 'remove_waiting_trades#create', as: :run_remove_waiting_trading
  end
  namespace :resque do
    resources :workers, only: %i(index)
    resources :worker_statuses, only: %i(index)
    resources :jobs, only: %i(destroy), param: :pid do
      delete :destroy_all, on: :collection
    end
  end
  resources :scalping_tasks, only: %i(index)
  resource :setting, only: %i(edit update)
  resources :results, only: :index do
    post :recalc, on: :collection
  end
  resources :api_call_logs, only: :index
  resources :preorder_snapshots do
    post :import_to_bf, on: :member
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  CACHE_KEY = 'last_succeed_at'

  def index
    recalc_if_need!
    @summarized_my_trades = BF::SummarizedMyTrade.where('summarized_on > ?', 2.week.ago).order(summarized_on: :desc)
    @total_summarized_my_trade = @summarized_my_trades.
      group(:summarized_on, :kind).
      select('sum(count) sum_count', 'sum(profit) sum_profit', 'kind').
      group_by(&:kind)
  end

  def recalc
    BF::SummarizedMyTrade.summarize!
    redirect_to results_path, notice: '再計算が完了しました'
  end

  def recalc_if_need!
    current_last_succeed_at = BF::MyTradeShip.last_succeed_at
    cached_last_succeed_at = Rails.cache.fetch(CACHE_KEY)
    if cached_last_succeed_at.nil?
      Rails.cache.write(CACHE_KEY, current_last_succeed_at)
    end
    unless cached_last_succeed_at == current_last_succeed_at
      BF::SummarizedMyTrade.summarize!
      Rails.cache.write(CACHE_KEY, current_last_succeed_at)
    end
  end
end

app/views/results/index.html.slim
h1 Result
p = link_to '再計算する', recalc_results_path, method: :post

table border=1
  tr
    th 日付
    th automation数
    th automation利益

    th
    th manual数
    th manual利益
    th 合計数
    th 合計利益
  - @summarized_my_trades.group_by(&:summarized_on).each do |date, summarized_my_trades|
    - automation = summarized_my_trades.detect { |x| x.automation? } || BF::SummarizedMyTrade.new
    - manual = summarized_my_trades.detect { |x| x.manual? } || BF::SummarizedMyTrade.new
    tr
      td = date
      td = automation.count
      td
        = automation.profit
        | 円
      td
      td = manual.count
      td
        = manual.profit
        | 円
      td = automation.count + manual.count
      td
        = automation.profit + manual.profit
        | 円
      manual
  tr
    td 合計
    - manual = @total_summarized_my_trade['manual'] || []
    - automation = @total_summarized_my_trade['automation'] || []
    td = manual.map(&:sum_count).sum
    td
      = manual.map(&:sum_profit).sum
      | 円
    td
    td = automation.map(&:sum_count).sum
    td
      = automation.map(&:sum_profit).sum
      | 円
    td = manual.map(&:sum_count).sum + automation.map(&:sum_count).sum
    td
      = manual.map(&:sum_profit).sum + automation.map(&:sum_profit).sum
      | 円