config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :charts, only: :index do
    get :day, on: :member
  end
  resources :prices, only: %i(index)
  resources :my_trades, only: %i(create) do
    member do
      put :cancel
    end
  end
  resources :my_trade_ships, only: %i(index)
  namespace :admin do
    resources :my_trades, only: %i(index) do
      delete :destroy_all, on: :collection
    end
  end
  namespace :api do
    resource :disparities, only: :show
    post 'run_one_scalping' => 'scalpings#create', as: :run_one_scalping
    post 'run_endless_scalping' => 'daemon_scalpings#create', as: :run_endless_scalping
    post 'run_remove_waiting_trading' => 'remove_waiting_trades#create', as: :run_remove_waiting_trading
  end
  namespace :resque do
    resources :workers, only: %i(index)
    resources :worker_statuses, only: %i(index)
    resources :jobs, only: %i(destroy), param: :pid do
      delete :destroy_all, on: :collection
    end
  end
  resources :scalping_tasks, only: %i(index)
  resource :setting, only: %i(edit update)
  resources :results, only: :index do
    post :recalc, on: :collection
  end
  resources :api_call_logs, only: :index
  resources :preorder_snapshots do
    post :import_to_bf, on: :member
  end
end

app/controllers/my_trade_ships_controller.rb
class MyTradeShipsController < ApplicationController
  def index
    respond_to do |format|
      format.html do
        @my_trade_ships = BF::MyTradeShip.
          includes(:buy_trade, :sell_trade, :scalping_task).
          order(id: :desc).page(params[:page])
      end
      format.js do
        @my_trade_ships = BF::MyTradeShip.recent
      end
    end
  end
end

app/views/my_trade_ships/_table.html.slim
css:
  [data-option-column=profit] { display: none; }

- unless defined?(show_checkbox)
  - show_checkbox = false
- if defined?(show_profit)
  - profit_object = MyTradeShipProfitObject.new(self, show_profit: show_profit)
- else
  - profit_object = MyTradeShipProfitObject.new(self, show_profit: false)

table border=1
  tr
    th
    th colspan=3 買い
    th colspan=3 売り
    = profit_object.table_first_header
    th data-option-column='profit'
    - if show_checkbox
      th
  tr
    th ship id
    th.span1 buy id
    th.span1 ステータス
    th 金額
    th.span1 sell id
    th.span1 ステータス
    th 金額
    th.span1 作成日
    = profit_object.table_middle_header
    th.span1 ソース
  - my_trade_ships.each do |my_trade_ship|
    tr class=css_class_of_trade_ship_status(my_trade_ship)
      td = my_trade_ship.id
      td = my_trade_ship.buy_trade_id
      td
        - if my_trade_ship.buy_trade.requested? || my_trade_ship.buy_trade.parted_trading?
          = link_to my_trade_ship.buy_trade.status, cancel_my_trade_path(my_trade_ship.buy_trade), data: { confirm: 'キャンセルしますが本当にいいですか？', remote: true }, method: :put
        - else
          = my_trade_ship.buy_trade.status.truncate(15)
      td = number_to_currency(my_trade_ship.buy_trade.price)
      td = my_trade_ship.sell_trade_id
      td
        - if my_trade_ship.sell_trade.nil?
          | sell_trade は未作成です
        - else
          = my_trade_ship.sell_trade.status.truncate(15)
      td = my_trade_ship.sell_trade && number_to_currency(my_trade_ship.sell_trade.price)
      td
        = distance_of_time_in_words_to_now(my_trade_ship.updated_at).truncate(13)
        | 前
      = profit_object.table_body do
        = number_to_currency(my_trade_ship.profit)
      td
        - if my_trade_ship.sell_trade.nil?
          | -
        - else
          = my_trade_ship.scalping_task ? :automation : :manual
      - if show_checkbox
        td
          = check_box_tag 'cheched_my_trade_ship_id[]', my_trade_ship.id

app/views/my_trade_ships/index.html.slim
h1 MyTradeShips

= paginate @my_trade_ships
= render 'table', my_trade_ships: @my_trade_ships, show_profit: true
= paginate @my_trade_ships

app/views/my_trade_ships/index.js.erb
$("#my_trade_table").html("<%= j render('my_trade_ships/table', my_trade_ships: @my_trade_ships, show_profit: true) %>");